// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {Groth16ProofAdapter} from "../src/adapters/Groth16ProofAdapter.sol";
import {Types} from "../src/libraries/Types.sol";
import {Errors} from "../src/libraries/Errors.sol";

/// @dev These fixtures are generated by zkapi-proof/examples/solidity_fixture.rs.
contract Groth16ProofAdapterTest is Test {
    Groth16ProofAdapter adapter;

    function setUp() public {
        adapter = new Groth16ProofAdapter();
    }

    function test_verifiesRustRequestProof() public view {
        adapter.assertValidRequest(_requestInputs(), _requestProof());
    }

    function test_rejectsTamperedRequestInput() public {
        Types.RequestPublicInputs memory inputs = _requestInputs();
        inputs.solvencyBound += 1;
        vm.expectRevert(Errors.InvalidProof.selector);
        adapter.assertValidRequest(inputs, _requestProof());
    }

    function test_verifiesRustWithdrawalProof() public view {
        adapter.assertValidWithdrawal(_withdrawalInputs(), _withdrawalProof());
    }

    function test_rejectsTamperedWithdrawalInput() public {
        Types.WithdrawalPublicInputs memory inputs = _withdrawalInputs();
        inputs.finalBalance -= 1;
        vm.expectRevert(Errors.InvalidProof.selector);
        adapter.assertValidWithdrawal(inputs, _withdrawalProof());
    }

    function _requestInputs() private pure returns (Types.RequestPublicInputs memory) {
        return Types.RequestPublicInputs({
            protocolVersion: 2,
            chainId: 31_337,
            contractAddress: address(0x1234),
            activeRoot: 0x26d72027b59772fef858b9a437de71ee70a1bb29fa96360d872f02d58f24dcc,
            stateSigningKeyX: 0x2b8cfd91b905cae31d41e7dedf4a927ee3bc429aad7e344d59d2810d82876c32,
            stateSigningKeyY: 0x2aaa6c24a758209e90aced1f10277b762a7c1115dbc0e16ac276fc2c671a861f,
            requestTime: 2_000_000_000,
            solvencyBound: 500_000,
            requestNullifier: 0x297c134bc2ba2db527d7d6cf5818de29f838328162eb1566546ec75916e6a33f,
            authorizationTag: 0xc1b5b2a9d987637dfd1aa6a8be187712bd9553040cce1518d80a45afb19cd92,
            anonymousCommitmentX: 0x219ed7c17d01c586f645a9f0e86b8b722d1558bacd4af05a3f1d7066cbcdfdb1,
            anonymousCommitmentY: 0x1171bfded8bb0c58def57a60eeb09f46c22c3557fc420b2374ec58a960d515b0
        });
    }

    function _withdrawalInputs() private pure returns (Types.WithdrawalPublicInputs memory) {
        return Types.WithdrawalPublicInputs({
            protocolVersion: 2,
            chainId: 31_337,
            contractAddress: address(0x1234),
            activeRoot: 0x26d72027b59772fef858b9a437de71ee70a1bb29fa96360d872f02d58f24dcc,
            stateSigningKeyX: 0x2b8cfd91b905cae31d41e7dedf4a927ee3bc429aad7e344d59d2810d82876c32,
            stateSigningKeyY: 0x2aaa6c24a758209e90aced1f10277b762a7c1115dbc0e16ac276fc2c671a861f,
            clearanceSigningKeyX: 0x1812b84c2101217b0939a2f542535075eeaa81d07dab701a899a55db26e85be4,
            clearanceSigningKeyY: 0xbe80d0f61a801533a94a03b12683474f86ca012941db1c568c53dc877b16fd6,
            noteId: 0,
            finalBalance: 1_000_000,
            destination: 0x1111111111111111111111111111111111111111,
            withdrawalNullifier: 0x297c134bc2ba2db527d7d6cf5818de29f838328162eb1566546ec75916e6a33f,
            hasClearance: false,
            withdrawalTag: 0x123f3153e77e64bd4f9f39fee5ccd8949d0e7bb8e62e487ddb8be6c7320d48be
        });
    }

    function _requestProof() private pure returns (bytes memory) {
        return hex"0e18f0d2a55bcce803e23805631d613db8b44ad30ed960a954d894370483da9f2547b59365f659521c2a78e936849c20ee021643becdc45df40f7ab410cc26a5062fc61b3711a742d1588ce3dd14006f96c5a26af75c5730ff8fc84af4b639691126546388e8843064598257679eea1990bf5691c3982cbf1afc896a7126aaec206d1a8a8c2071908ef59c3af583a6e11c7a6a4ccf8098140b3771a6087ec81422fa9c14c5306554cf38e0045bb299b2dafddf30886257e6a9a5c622add5a9932147ab258273bd008af23cbd199ec27e63d29bbf9df57eddd5e222dc8a00de101120463037de94672da6e9e8285dcc2fb4fb9e4c82c87d3663678936cde3f28d";
    }

    function _withdrawalProof() private pure returns (bytes memory) {
        return hex"0da835587df846ecafb4001360feae2d7c9f88a65625e0923e24ff88d504e1be04c25d1a4a17d3f8003a0c0b05720f6594c6824301fbcb869b7ab75ebf5a8d1a28d2e74d30bab5c6bccaa4bfdd67648a6d00204ec72bf4ff68b6cbc69fb4b809120603b590733733b0d68bb8582bc084dfee9a8d5cb6237ac2b8d39696a2e4501cd4edf2df21a4f436517ee20e4ebee796b19edbe1dc2480956eec9eb5964a022827a0b99a790fc46ad7148619624ca315ca230a8a0d5dec2e7286d61dcec672142a8143a6f3e295096c25a860b323f161e3666948224a53f97dcead6cd2aa5e1c4c70427846969e8da931a260337cd6613b8ba60fb53826b7e7f360ecd75092";
    }
}
