// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {Groth16ProofAdapter} from "../src/adapters/Groth16ProofAdapter.sol";
import {Types} from "../src/libraries/Types.sol";
import {Errors} from "../src/libraries/Errors.sol";

/// @dev These fixtures are generated by zkapi-proof/examples/solidity_fixture.rs.
contract Groth16ProofAdapterTest is Test {
    Groth16ProofAdapter adapter;

    function setUp() public {
        adapter = new Groth16ProofAdapter();
    }

    function test_verifiesRustRequestProof() public view {
        adapter.assertValidRequest(_requestInputs(), _requestProof());
    }

    function test_rejectsTamperedRequestInput() public {
        Types.RequestPublicInputs memory inputs = _requestInputs();
        inputs.solvencyBound += 1;
        vm.expectRevert(Errors.InvalidProof.selector);
        adapter.assertValidRequest(inputs, _requestProof());
    }

    function test_verifiesRustWithdrawalProof() public view {
        adapter.assertValidWithdrawal(_withdrawalInputs(), _withdrawalProof());
    }

    function test_rejectsTamperedWithdrawalInput() public {
        Types.WithdrawalPublicInputs memory inputs = _withdrawalInputs();
        inputs.finalBalance -= 1;
        vm.expectRevert(Errors.InvalidProof.selector);
        adapter.assertValidWithdrawal(inputs, _withdrawalProof());
    }

    function _requestInputs() private pure returns (Types.RequestPublicInputs memory) {
        return Types.RequestPublicInputs({
            protocolVersion: 2,
            chainId: 31_337,
            contractAddress: address(0x1234),
            activeRoot: 0x26d72027b59772fef858b9a437de71ee70a1bb29fa96360d872f02d58f24dcc,
            stateSigningKeyX: 0x2b8cfd91b905cae31d41e7dedf4a927ee3bc429aad7e344d59d2810d82876c32,
            stateSigningKeyY: 0x2aaa6c24a758209e90aced1f10277b762a7c1115dbc0e16ac276fc2c671a861f,
            requestTime: 2_000_000_000,
            solvencyBound: 500_000,
            requestNullifier: 0x297c134bc2ba2db527d7d6cf5818de29f838328162eb1566546ec75916e6a33f,
            authorizationTag: 0xc1b5b2a9d987637dfd1aa6a8be187712bd9553040cce1518d80a45afb19cd92,
            anonymousCommitmentX: 0x1f150009fb80340eb8155ca9b304faec3a5fcc2886405617362164736262ad41,
            anonymousCommitmentY: 0x133b9e7c67d2c3b35c702c96b67dc43faec807fc96ee12affe70f1e2a43fd551
        });
    }

    function _withdrawalInputs() private pure returns (Types.WithdrawalPublicInputs memory) {
        return Types.WithdrawalPublicInputs({
            protocolVersion: 2,
            chainId: 31_337,
            contractAddress: address(0x1234),
            activeRoot: 0x26d72027b59772fef858b9a437de71ee70a1bb29fa96360d872f02d58f24dcc,
            stateSigningKeyX: 0x2b8cfd91b905cae31d41e7dedf4a927ee3bc429aad7e344d59d2810d82876c32,
            stateSigningKeyY: 0x2aaa6c24a758209e90aced1f10277b762a7c1115dbc0e16ac276fc2c671a861f,
            clearanceSigningKeyX: 0x1812b84c2101217b0939a2f542535075eeaa81d07dab701a899a55db26e85be4,
            clearanceSigningKeyY: 0xbe80d0f61a801533a94a03b12683474f86ca012941db1c568c53dc877b16fd6,
            noteId: 0,
            finalBalance: 1_000_000,
            destination: 0x1111111111111111111111111111111111111111,
            withdrawalNullifier: 0x297c134bc2ba2db527d7d6cf5818de29f838328162eb1566546ec75916e6a33f,
            hasClearance: false,
            withdrawalTag: 0x123f3153e77e64bd4f9f39fee5ccd8949d0e7bb8e62e487ddb8be6c7320d48be
        });
    }

    function _requestProof() private pure returns (bytes memory) {
        return hex"069c40e981f13519d6b1ab8698b89d62a29c736858a70ea1f70769a1b38d45050b38f20386b26add396e9b73ef4ee9c98f1aabb41864e6e267789932cb04a7de26b5b10c51dcac23fc0299e15a63aeb96c14efdad0dc3ad04f23aba57e61077922f2dcf750147c9eb12deb310d0909f2031054305206710fcdbd996566779e09103967a2728c7e2f1322ba16e1dcf28c0ae3959143d0116c80a48b095654aabe202eae220320bab324a8a5107e8d3fc16a25aa6993863bd67c1f721325c6d59b0b2b1c4f4aab6b68ffe8edf3663d685bbd98adb65ef16eccd8255f3b98e2ffc02002dfb2272aed1b331cec19f39ef4eef96ee5ee2b4dfdaaa3b3165d5333a9c7";
    }

    function _withdrawalProof() private pure returns (bytes memory) {
        return hex"05901ab80b16f3a9430342145055a8139f7c9b86a4ca65811e5ec123b7793c6909378fb4a80237ac14fa39ebe7fc1dc6f75d4a0af6cbd7e1f4630447d88b72dd029ebb5c39100ef5bda2285cceede0e2e4e088eadf00904e7d63187712245e5100951efdbfd5a91fffee64b782b4e056670cf7e5b25ce00f70444a9ec14d19d025a5fca4f6cacdb171b5b19dc0501463a3976c61a50cf2a66602af6077ddc56c217294a5febd08879da433bc4620c9ea522f70e55b533328b38afe0e6e373d282d4cfa9ce0a421d944d69270208d7245eec5f7fa4c76350ca73c89bf2a2a83881bb87333801e45bff97bfa0b30607f8082edce93f875819763b4df559ef7eebe";
    }
}
