[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 10000
ffi = false
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 50
